language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_IMAGE=matrix-synapse
    - LATEST=0.33.4
  matrix:
    - VERSION=0.33.4
    - VERSION=0.32.2
    - VERSION=0.31.2
    - VERSION=0.30.0


before_script:
  - sudo ./ci/install-docker.sh

install: true

script:
  - docker build --build-arg=SYNAPSE_VERSION=${VERSION} -t ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${VERSION} ./
  - docker-compose -f ./ci/docker-compose.yml up -d
  - retry -i 10s -c 6 bash -c "curl -IL http://localhost | grep '200 OK'"

before_deploy:
  - ./ci/docker-login.sh

deploy:
  provider: script
  script: ./ci/deploy.sh
  on:
    branche: master
