language: generic
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_IMAGE=matrix-synapse
    - LATEST=0.33.7
  matrix:
    - VERSION=0.33.7
    - VERSION=0.32.2
    - VERSION=0.31.2
    - VERSION=0.30.0


before_script:
  - sudo ./install-docker.sh

install: true

script:
  - docker build --build-arg=SYNAPSE_VERSION=${VERSION} -t ${DOCKER_USERNAME}/${DOCKER_IMAGE}:${VERSION} ./

before_deploy:
  - ./docker-login.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    all_branches: true
