version: "3"

services:
  synapse:
    image: johannweging/matrix-synapse:latest
    labels:
      traefik.backend: synapse
      traefik.frontend.rule: Host:localhost
      traefik.port: "8008"
      traefik.enable: "true"
    environment:
      SERVER_NAME: localhost
      WEB_CLIENT: "true"
      ENABLE_REGISTRATION: "true"
    ports:
      - "8448:8448"

  traefik:
    image: traefik:latest
    command: >
      --docker
      --docker.watch
      --docker.exposedbydefault=false
      --entrypoints='Name:https Address::443 TLS'
      --defaultentrypoints=https
      --web
      -l info
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped


