#!/bin/sh

mkdir -p conf
chown synapse:synapse /conf

gosu synapse /usr/bin/python2 -m synapse.app.homeserver --config-path /conf/default.yaml \
	--generate-config --report-stats no --server-name localhost > /dev/null


echo "MACAROON_SECRET_KEY=$(cat /conf/default.yaml | grep macaroon_secret_key | cut -d ':' -f 2 | tr -d ' \n')"
echo "SIGNING_KEY=\"$(cat /conf/localhost.signing.key)\""
echo "PASSWORD_CONFIG_PEPPER=$(cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"

